### ISSUE TITLE
How does the app server runs on 8000 port?

### ISSUE THREAD

**Issue by slim-hmidi** [austincunningham/keycloak-express#1]
I realized that in your code you give the app's server a port `8080` and in the demo you put `8000`. It works for me on the port `8000`.But I'm not able to connect using keycloak server.How does the server runs?

**Comment by austincunningham** [comment]
Thanks for taking the time to open an issue
You are correct the keycloak server runs on 8080 so you can't use that port for the express app so.
https://github.com/austincunningham/keycloak-express/blob/ed16c6ef66b33fc915445d29ff374b7ca71b97ea/app.js#L51
should be 
```
app.listen(8000, function () {
  console.log('Listening at http://localhost:8000');
});
```
 Has been some time since I looked at this and there have been a few releases of Keycloak in the mean time.  The keycloak.json would now be in the following format 
```
{
  "realm": "test",
  "auth-server-url": "http://localhost:8080/auth",
  "ssl-required": "external",
  "resource": "keycloak-express",
  "public-client": true,
  "confidential-port": 0
}
```
Also it looks like keycloak now requires the client to have a valid redirect url 
![image](https://user-images.githubusercontent.com/16667688/39455025-4e49871a-4cd6-11e8-8310-a51c7f1864bd.png)

**Comment by austincunningham** [comment]
resolved in https://github.com/austincunningham/keycloak-express/pull/2

**Comment by slim-hmidi** [comment]
@austincunningham  good job 👍
